AWSTemplateFormatVersion: "2010-09-09"
Description: Regional Lambda Layers for Carve

Parameters:
  OrganizationsId:
    Type: String
    Description: AWS Organizations Id
    Default: ""
  ResourcePrefix:
    Type: String
    Description: "Prefix all carve resources with this"
    Default: ""
  S3Bucket:
    Type: String
    Description: Bucket with deploy artifact
  GITSHA:
    Type: String
    Default: ""
    Description: latest Git commit SHA determines S3 artifact paths

Resources:
  RequirementsLayer:
    Type: AWS::Lambda::LayerVersion
    Properties: 
      CompatibleRuntimes:
        - python3.8
      Content: 
        S3Bucket: !Ref S3Bucket
        S3Key: !Sub "lambda_packages/${GITSHA}/reqs_package.zip"
        # S3Key: "requirements_packages/b1381f2c51b3877528a5d14436f4267a45071946/requirements_package.zip"
      Description: "Carve python requirements"
      LayerName: CarveRequirementsLayer

  LayerPermission:
    Type: AWS::Lambda::LayerVersionPermission
    Properties: 
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref RequirementsLayer
      OrganizationId: !Ref OrganizationsId
      Principal: "*"