version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
  build:
    commands:
      - export BUILDPATH=$(pwd)
      - cd deployment/codepipeline/scripts/
      - chmod 443 package.sh
      # Build carve lambda packages and send to s3
      - ./package.sh