AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role For Every AWS Account Running Carve

Parameters:

  OrganizationsId:
    Type: String
    Description: AWS Organizations Id
    Default: ""

  ResourcePrefix:
    Type: String
    Description: "Prefix all carve resources with this"
    Default: ""

Resources:

  CarveIamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ResourcePrefix}carve-lambda-${OrganizationsId}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Principal:
            Service:
              - "lambda.amazonaws.com"
              - "ec2.amazonaws.com"
          Action:
            - "sts:AssumeRole"
        - Effect: Allow
          Action:
            - sts:AssumeRole
          Principal:
            AWS: '*'
          Condition:
            ForAnyValue:StringEquals:
              aws:PrincipalOrgID: !Sub '${OrganizationsId}'
      Policies:
        - PolicyName: CarvePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:Invoke*
                Resource:
                  - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${ResourcePrefix}carve-vpc-*"
              - Effect: Allow
                Action:
                  - iam:PassRole
                  - iam:GetRole
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - organizations:ListAccounts
                Resource: "*"
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource:
                  - !Sub "arn:aws:iam::*:role/${ResourcePrefix}carve-lambda-${OrganizationsId}"
              # - Effect: "Allow"
              #   Action:
              #     - "sns:Subscribe"
              #     - "sns:Receive"
              #     - "sns:Publish"
              #   Resource: 
              #     - "*"
              - Effect: Allow
                Action:
                  - ec2:DescribeNetworkInterfaces
                  - ec2:CreateNetworkInterface
                  - ec2:DeleteNetworkInterface
                  - ec2:DescribeInstances
                  - ec2:AttachNetworkInterface
                  - ec2:DescribeVpcPeeringConnections
                  - ec2:DescribeVpcs
                  - ec2:DescribeRegions
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !Sub "arn:aws:s3:::${ResourcePrefix}carve-${OrganizationsId}-*"



