AWSTemplateFormatVersion: '2010-09-09'
Description: Account Resources For Carve

Parameters:

  OrgId:
    Type: String
    Description: AWS Organizations Id
    Default: ""

  CarveCoreAccount:
    Type: String
    Description: AWS Organizations Root AccountId
    Default: ""

  Prefix:
    Type: String
    Description: "Prefix all carve resources with this"
    Default: ""

Resources:

  CarveCoreRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Prefix}carve-core"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Action:
            - sts:AssumeRole
          Principal:
            AWS: [!Sub "arn:aws:iam::${CarveCoreAccount}:assumed-role/${Prefix}carve-core/carve-core"]
      Policies:
        - PolicyName: CarvePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "*"
                Resource:
                  - "*"
                # Condition:
                #   ForAnyValue:StringEquals:
                #     aws:CalledVia:
                #       - cloudformation.amazonaws.com               




